import type { Metadata } from "next";
import { Manrope, Merriweather, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/themes-provider";
import { Toaster } from "@/components/ui/sonner";

export const manrope = Manrope({ subsets: ["latin"], variable: "--font-sans" });
export const merri = Merriweather({
	subsets: ["latin"],
	variable: "--font-serif",
});
export const robomono = Roboto_Mono({
	subsets: ["latin"],
	variable: "--font-mono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${manrope.variable} ${merri.variable} ${robomono.variable}`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					{children}
					<Toaster closeButton />
				</ThemeProvider>
			</body>
		</html>
	);
}
